### ISSUE TITLE
Participação

### ISSUE THREAD

**Issue by rodrigondec** [daal-imd-dev/integraTI-api#2]
Gostaria de saber quem vai participar do desenvolvimento da aplicação e como será o fluxo de trabalho.

Acabei de configurar o docker no projeto no PR #1 e queria saber da visão de vocês se está tudo ok.

@Mazuh @DavidCardoso

**Comment by DavidCardoso** [comment]
Não poderei participar ativamente do desenvolvimento. Contudo, permaneço à disposição para contribuir de outras formas.

**Comment by Mazuh** [comment]
Não consigo participar de forma proativa, nem revisnado PRs grandes, mas se me atribuirem tarefas de desenvolvimento, eu faço.
