### ISSUE TITLE
Permissão de gerenciamento da equipe

### ISSUE THREAD

**Issue by rodrigondec** [daal-imd-dev/integraTI-api#3]
Gostaria de ter acesso ao ```daal-imd``` para poder gerenciar as equipe de desenvolvimento e ter acesso à ferramentas tais como o ```CircleCI``` dos projetos.

@gellyviana @daal-imd

**Comment by daal-imd** [comment]
Acredito que agora é migrar o repositório para o team Integra-TI

**Comment by daal-imd** [comment]
@rodrigondec deu certo? Elaboramos um questionário com base neste https://docs.google.com/document/d/1L_6yTFrKop8K5awIKEtEroY_871eCrtnyNHgmcuBDKM/edit?usp=sharing 
Espero que contemple boa parte do que pretendemos atacar.
